name: 'Add New Provider'

on:
  workflow_dispatch:
    inputs:
      new_provider:
        required: true
      pr_title:
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  add_provider_job:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Rep.'
        uses: actions/checkout@v4

      - name: 'Conf Git'
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions-bot@users.noreply.github.com"

      - name: 'Create new branch'
        run: git checkout -b "feature/auto-create-${{ github.event.inputs.new_provider }}"

      - name: 'Add providers using awk (Robust Method)'
        run: |
          # A linha a ser inserida é passada para o awk como uma variável
          LINE_TO_INSERT='        "${{ github.event.inputs.new_provider }}",'
          
          echo "Adding ${{ github.event.inputs.new_provider }} to tf/test_1.tf"
          awk -v line="$LINE_TO_INSERT" '
            /atr_list_2/ { in_block=1 }
            in_block && /^[[:space:]]*])$/ {
              print line;
              in_block=0;
            }
            { print }
          ' tf/test_1.tf > tmp1.tf && mv tmp1.tf tf/test_1.tf

          echo "Adding ${{ github.event.inputs.new_provider }} to tf/test_2.tf"
          awk -v line="$LINE_TO_INSERT" '
            /atr_list_2/ { in_block=1 }
            in_block && /^[[:space:]]*])$/ {
              print line;
              in_block=0;
            }
            { print }
          ' tf/test_2.tf > tmp2.tf && mv tmp2.tf tf/test_2.tf

      - name: 'Commit & Push'
        run: |
          git add tf/test_1.tf tf/test_2.tf
          git commit -m "feat: create ${{ github.event.inputs.new_provider }} provider"
          git push origin "feature/auto-create-${{ github.event.inputs.new_provider }}"

      - name: 'Create, approve and merge PR'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH_NAME="feature/auto-create-${{ github.event.inputs.new_provider }}-${{ github.run_id }}"

          echo "Creating PR..."
          gh pr create \
            --title "${{ github.event.inputs.pr_title }}" \
            --body "Add the new provider **${{ github.event.inputs.new_provider }}**. This PR will be merged automatically." \
            --base main
          
          echo "Approving PR..."
          gh pr review "$BRANCH_NAME" --approve --body "Aproved by GitHub Actions Workflow"
          
          echo "Merging PR..."
          gh pr merge "$BRANCH_NAME" --auto --merge