name: 'Add New Provider'

on:
  workflow_dispatch:
    inputs:
      new_provider:
        required: true
      pr_title:
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  add_provider_job:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Rep.'
        uses: actions/checkout@v4

      - name: 'Conf Git'
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions-bot@users.noreply.github.com"

      - name: 'Create new branch'
        run: git checkout -b "feature/auto-create-${{ github.event.inputs.new_provider }}"

      - name: 'Add providers'
        run: |
          LINE_TO_INSERT='        "${{ github.event.inputs.new_provider }}",'
          
          echo "Adding ${{ github.event.inputs.new_provider }} to tf/test_1.tf"
          sed -i -e '/atr_list_2/,/^[[:space:]]*])$/{ /^[[:space:]]*])$/ i\'"$LINE_TO_INSERT"' -e '}' tf/test_1.tf
          
          echo "Adding ${{ github.event.inputs.new_provider }} to tf/test_2.tf"
          sed -i -e '/atr_list_2/,/^[[:space:]]*])$/{ /^[[:space:]]*])$/ i\'"$LINE_TO_INSERT"' -e '}' tf/test_2.tf

      - name: 'Commit & Push'
        run: |
          git add tf/test_1.tf tf/test_2.tf
          git commit -m "feat: create ${{ github.event.inputs.new_provider }} provider"
          git push origin "feature/auto-create-${{ github.event.inputs.new_provider }}"

      - name: 'Create, approve and merge PR'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --title "${{ github.event.inputs.pr_title }}" \
            --base main
          
          gh pr merge "feat/add-tf-${{ github.event.inputs.new_provider }}" --approve --auto --merge